#!/bin/bash

steamargs=("-steamos3" "-steampal" "-steamdeck" "-gamepadui")
if [[ -x $HOME/devkit-game/devkit-steam ]]; then
	exec steam -silent
	exec "$HOME"/devkit-game/devkit-steam
else
	exec steam "${steamargs[@]}"
fi
